"use client";

import { useState } from "react";
import type { JobMatchDto } from "./types";
import { InterviewInvitationForm } from "./InterviewInvitationForm";

export function JobMatchCard({
  match,
  dragHandleProps,
}: {
  match: JobMatchDto;
  dragHandleProps: Record<string, unknown>;
}) {
  const [guideContent, setGuideContent] = useState(
    match.interviewGuide?.guideContent ?? null,
  );
  const [showGuide, setShowGuide] = useState(false);

  const cv = match.documents.find((d) => d.type === "CV");
  const coverLetter = match.documents.find((d) => d.type === "COVER_LETTER");

  return (
    <div className="rounded-md border border-black/[.1] bg-white p-3 text-sm shadow-sm dark:border-white/[.15] dark:bg-zinc-900">
      <div className="mb-1 flex items-start justify-between gap-2">
        <div>
          <p className="font-medium">{match.jobTitle}</p>
          <p className="text-zinc-500">{match.employer}</p>
        </div>
        <span
          {...dragHandleProps}
          className="cursor-grab select-none text-zinc-400"
          aria-label="Dra för att flytta kortet"
        >
          ⠿
        </span>
      </div>

      <a
        href={match.url}
        target="_blank"
        rel="noopener noreferrer"
        className="text-xs underline"
      >
        Visa annons
      </a>

      {match.deadline && (
        <p className="mt-1 text-xs text-zinc-500">
          Sista ansökningsdag:{" "}
          {new Date(match.deadline).toLocaleDateString("sv-SE")}
        </p>
      )}

      <div className="mt-2 flex gap-3 text-xs">
        {cv && (
          <a href={cv.pdfUrl} target="_blank" rel="noopener noreferrer" className="underline">
            Ladda ner CV
          </a>
        )}
        {coverLetter && (
          <a
            href={coverLetter.pdfUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
          >
            Ladda ner brev
          </a>
        )}
      </div>

      <div className="mt-3">
        {guideContent ? (
          <>
            <button
              type="button"
              onClick={() => setShowGuide((v) => !v)}
              className="text-sm font-medium underline"
            >
              {showGuide ? "Dölj intervjuguide" : "Visa intervjuguide"}
            </button>
            {showGuide && (
              <div
                className="prose prose-sm mt-2 max-w-none dark:prose-invert"
                // Content is generated by Claude and sanitized server-side
                // (allowlist of basic tags only) before being stored.
                dangerouslySetInnerHTML={{ __html: guideContent }}
              />
            )}
          </>
        ) : (
          <InterviewInvitationForm
            jobMatchId={match.id}
            onGuideReady={(content) => {
              setGuideContent(content);
              setShowGuide(true);
            }}
          />
        )}
      </div>
    </div>
  );
}
